"""add staff-client association table

Revision ID: 267818294c3c
Revises: 4ee2d7fe82c4
Create Date: 2026-05-02 09:00:19.374973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267818294c3c'
down_revision = '4ee2d7fe82c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_clients',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_clients')
    # ### end Alembic commands ###
